<?xml version="1.0"?>
<robot name="husky_with_chemical_sensor" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- <property name="sensor_height" value="${base_z_size/5}" /> -->
    <!-- <xacro:arg name="my" default="1.0" /> -->
    <xacro:property name="sensor_height" value="${base_z_size/5}" />

    <link name="sensor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size/10} ${base_y_size/2} ${sensor_height}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size/10} ${base_y_size/2} ${sensor_height}" />
            </geometry>
        </collision>
    </link>

    <joint name="sensor_link_joint" type="fixed">
        <origin xyz="0 0 ${base_z_size + sensor_height/2}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="sensor_link" />
    </joint>
</robot>